version: '2'
services:
  web:
    build: .
    command: yarn run test-watch
    volumes:
      - ./:/usr/local/src
      - listsdk_node_modules:/usr/local/src/node_modules
    restart: always
    environment:
      - NODE_ENV=test
volumes:
  listsdk_node_modules:
    external: true
